# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OpenWeather
                                 A QGIS plugin
 Downloading Weather Data From OpenWeather API
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-02-17
        copyright            : (C) 2022 by Htet Arkar Soe
        email                : htetarkar.env.2016@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Htet Arkar Soe'
__date__ = '2022-02-17'
__copyright__ = '(C) 2022 by Htet Arkar Soe'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OpenWeather class from file OpenWeather.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .OpenWeather import OpenWeatherPlugin
    return OpenWeatherPlugin(iface)