# -*- coding: utf-8 -*-

"""
/***************************************************************************
 OpenWeather
                                 A QGIS plugin
 Downloading Weather Data From OpenWeather API
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-02-17
        copyright            : (C) 2022 by Htet Arkar Soe
        email                : htetarkar.env.2016@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Htet Arkar Soe'
__date__ = '2022-02-17'
__copyright__ = '(C) 2022 by Htet Arkar Soe'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import requests
import datetime
import time
import json
import csv
import os
import processing
import inspect

from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFileDestination,
                       QgsProcessingMultiStepFeedback,
                       QgsProcessingParameterPoint,
                       QgsProcessingParameterString,
                       QgsCoordinateReferenceSystem,
                       QgsExpression,
                       QgsExpressionContext,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterEnum,
                       QgsSettings)

#from .functions import wind_deg, wind_speed

class OpenWeatherAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """
        my_settings = QgsSettings()
        my_api_key = my_settings.value("openWeather_api", "")
        if my_api_key=="":
            api_key_text = 'Enter your API key '
        else:
            api_key_text = 'Enter your API key or use existing one below'
        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(QgsProcessingParameterPoint('ChooseLocationOnMap', 'Choose Location On Map', defaultValue=''))
        #self.addParameter(QgsProcessingParameterFeatureSource(self.INPUT,self.tr('Input layer'),[QgsProcessing.TypeVectorAnyGeometry]))
        #self.addParameter(QgsProcessingParameterFileDestination(self.OUTPUT,self.tr('Output File'),'CSV files (*.csv)'))
        self.addParameter(QgsProcessingParameterEnum('DataType', 'Select OpenWeatherData to download', 
                            options=['Weather Data (Current)','Air Pollution (Current)'], 
                            allowMultiple=False, defaultValue=None
                            ))
        self.addParameter(QgsProcessingParameterString('API_key', api_key_text, multiLine=False, defaultValue=my_api_key))
        self.addParameter(QgsProcessingParameterFeatureSink('WeatherResult', 'Output Point Layer', type=QgsProcessing.TypeVectorAnyGeometry, createByDefault=True, supportsAppend=True, defaultValue=None))
        
    def processAlgorithm(self, parameters, context, model_feedback):
        """
        Here is where the processing itself takes place.
        """
        my_settings = QgsSettings()
        feedback = QgsProcessingMultiStepFeedback(3, model_feedback)
        results = {}
        outputs = {}
        
        source = parameters['ChooseLocationOnMap']
        #csvOutput = self.parameterAsFileOutput(parameters, self.OUTPUT, context)
        
        ## DownloadJSON
        epsg = source.split(' ')[1]
        epsg = epsg[1:-1] # strip off [ ]
        #print (epsg)
        points = source.split(' ')[0].split(',')
        lat = points[1]
        lon = points[0]
        if not(epsg=='EPSG:4326'):
            lat_exp =  f'y(transform(make_point({lat},{lon}),\'{epsg}\',\'EPSG:4326\'))'
            lon_exp =  f'x(transform(make_point({lat},{lon}),\'{epsg}\',\'EPSG:4326\'))'
            context_exp = QgsExpressionContext()
            
            lat = QgsExpression(lat_exp).evaluate(context_exp)
            lon = QgsExpression(lon_exp).evaluate(context_exp)
        
        data_types = ['weather?','air_pollution?']

        datatype = data_types[parameters['DataType']]
        my_settings.setValue("openWeather_api", parameters['API_key'])
        apikey = parameters['API_key']
        latlon = {'lat':lat, 'lon':lon, 'appid':apikey}
        r = requests.get(f'http://api.openweathermap.org/data/2.5/{datatype}',params=latlon)
        data = r.json()

        ## Create Variables for weather data
        if datatype == 'weather?':
            speed = list(data['wind'].values())[0]
            deg = list(data['wind'].values())[1]
            avg_temp = list(data['main'].values())[0]
            feel_temp = list(data['main'].values())[1]
            min_temp = list(data['main'].values())[2]
            max_temp = list(data['main'].values())[3]
            pressure = list(data['main'].values())[4]
            humidity = list(data['main'].values())[5]
            dt = data['dt']
            #dt = datetime.datetime.fromtimestamp(dt1).strftime("%c")

            
        
        else:
            co = list(data['list'][0]['components'].values())[0]
            no = list(data['list'][0]['components'].values())[1]
            no2 = list(data['list'][0]['components'].values())[2]
            o3 = list(data['list'][0]['components'].values())[3]
            so2 = list(data['list'][0]['components'].values())[4]
            pm25 = list(data['list'][0]['components'].values())[5]
            pm10 = list(data['list'][0]['components'].values())[6]
            nh3 = list(data['list'][0]['components'].values())[7]
            dt = data['list'][0]['dt']
            #dt = datetime.datetime.fromtimestamp(dt1).strftime("%c")


                      
        # Create layer from point
        alg_params = {
            'INPUT': parameters['ChooseLocationOnMap'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['CreateLayerFromPoint'] = processing.run('native:pointtolayer', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(1)
        if feedback.isCanceled():
            return {}

        # Add X/Y fields to layer
        alg_params = {
            'CRS': QgsCoordinateReferenceSystem('EPSG:4326'),
            'INPUT': outputs['CreateLayerFromPoint']['OUTPUT'],
            'PREFIX': '',
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['AddXyFieldsToLayer'] = processing.run('native:addxyfields', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
        
        feedback.setCurrentStep(2)
        if feedback.isCanceled():
            return {}
            
        # calculateA: windspeed and carbon monoxide (CO)
        if datatype == 'weather?':
            alg_params = {
                'FIELD_LENGTH': 10,
                'FIELD_NAME': 'windspeed',
                'FIELD_PRECISION': 4,
                'FIELD_TYPE': 0,
                'FORMULA': speed,
                'INPUT': outputs['AddXyFieldsToLayer']['OUTPUT'],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
        else:
            alg_params = {
                'FIELD_LENGTH': 15,
                'FIELD_NAME': 'co_μg/m3',
                'FIELD_PRECISION': 4,
                'FIELD_TYPE': 0,
                'FORMULA': co,
                'INPUT': outputs['AddXyFieldsToLayer']['OUTPUT'],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
        outputs['calculateA'] = processing.run('native:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
        
        feedback.setCurrentStep(3)
        if feedback.isCanceled():
            return {}
            
        # calculateB: winddirection & nitrogen monoxide (NO)
        if datatype == 'weather?':
            alg_params = {
                'FIELD_LENGTH': 15,
                'FIELD_NAME': 'winddirection',
                'FIELD_PRECISION': 0,
                'FIELD_TYPE': 1,
                'FORMULA': deg,
                'INPUT': outputs['calculateA']['OUTPUT'],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        else:
            alg_params = {
                'FIELD_LENGTH': 15,
                'FIELD_NAME': 'no_μg/m3',
                'FIELD_PRECISION': 4,
                'FIELD_TYPE': 0,
                'FORMULA': no,
                'INPUT': outputs['calculateA']['OUTPUT'],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
        outputs['calculateB'] = processing.run('native:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
        
        #calculateC: Average_Temperature & Nitrogen dioxide (NO2)
        if datatype == 'weather?':
            alg_params = {
                'FIELD_LENGTH': 15,
                'FIELD_NAME': 'avg_temp',
                'FIELD_PRECISION': 0,
                'FIELD_TYPE': 0,
                'FORMULA': avg_temp,
                'INPUT': outputs['calculateB']['OUTPUT'],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
        else:
            alg_params = {
                'FIELD_LENGTH': 15,
                'FIELD_NAME': 'no2_μg/m3',
                'FIELD_PRECISION': 4,
                'FIELD_TYPE': 0,
                'FORMULA': no2,
                'INPUT': outputs['calculateB']['OUTPUT'],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
        outputs['calculateC'] = processing.run('native:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
        
        feedback.setCurrentStep(4)
        if feedback.isCanceled():
            return {}

        # calculateD: feels_like temperature & Ozone (O3)
        if datatype == 'weather?':
            alg_params = {
                'FIELD_LENGTH': 15,
                'FIELD_NAME': 'feel_temp',
                'FIELD_PRECISION': 0,
                'FIELD_TYPE': 0,
                'FORMULA': feel_temp,
                'INPUT': outputs['calculateC']['OUTPUT'],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
        else:
            alg_params = {
                'FIELD_LENGTH': 15,
                'FIELD_NAME': 'o3_μg/m3',
                'FIELD_PRECISION': 4,
                'FIELD_TYPE': 0,
                'FORMULA': o3,
                'INPUT': outputs['calculateC']['OUTPUT'],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
        outputs['calculateD'] = processing.run('native:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
        
        feedback.setCurrentStep(5)
        if feedback.isCanceled():
            return {}

        #calculateE: minimum temperature & Sulphur Dioxide (SO2)
        if datatype == 'weather?':
            alg_params = {
                'FIELD_LENGTH': 15,
                'FIELD_NAME': 'min_temp',
                'FIELD_PRECISION': 0,
                'FIELD_TYPE': 1,
                'FORMULA': min_temp,
                'INPUT': outputs['calculateD']['OUTPUT'],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
        else:
            alg_params = {
                'FIELD_LENGTH': 15,
                'FIELD_NAME': 'so2_μg/m3',
                'FIELD_PRECISION': 4,
                'FIELD_TYPE': 0,
                'FORMULA': so2,
                'INPUT': outputs['calculateD']['OUTPUT'],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
        outputs['calculateE'] = processing.run('native:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
        
        # calculateF: maximum temperature & fine particulate matters (PM2.5)
        if datatype == 'weather?':
            alg_params = {
                'FIELD_LENGTH': 10,
                'FIELD_NAME': 'max_temp',
                'FIELD_PRECISION': 0,
                'FIELD_TYPE': 0,
                'FORMULA': max_temp,
                'INPUT': outputs['calculateE']['OUTPUT'],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
        else:
            alg_params = {
                'FIELD_LENGTH': 15,
                'FIELD_NAME': 'pm25_μg/m3',
                'FIELD_PRECISION': 4,
                'FIELD_TYPE': 0,
                'FORMULA': pm25,
                'INPUT': outputs['calculateE']['OUTPUT'],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
        outputs['calculateF'] = processing.run('native:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
        
        # calculateG: pressure & coarse particulate matters (PM10)
        if datatype == 'weather?':
            alg_params = {
                'FIELD_LENGTH': 10,
                'FIELD_NAME': 'pressure',
                'FIELD_PRECISION': 0,
                'FIELD_TYPE': 1,
                'FORMULA': pressure,
                'INPUT': outputs['calculateF']['OUTPUT'],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
        else:
            alg_params = {
                'FIELD_LENGTH': 15,
                'FIELD_NAME': 'pm10_μg/m3',
                'FIELD_PRECISION': 4,
                'FIELD_TYPE': 0,
                'FORMULA': pm10,
                'INPUT': outputs['calculateF']['OUTPUT'],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
        outputs['calculateG'] = processing.run('native:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
        
        # calculateH: humidity & Nitrogen Monoxide (NH3)
        if datatype == 'weather?':
            alg_params = {
                'FIELD_LENGTH': 10,
                'FIELD_NAME': 'humidity',
                'FIELD_PRECISION': 0,
                'FIELD_TYPE': 1,
                'FORMULA': humidity,
                'INPUT': outputs['calculateG']['OUTPUT'],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
        else:
            alg_params = {
                'FIELD_LENGTH': 15,
                'FIELD_NAME': 'nh3_μg/m3',
                'FIELD_PRECISION': 4,
                'FIELD_TYPE': 0,
                'FORMULA': nh3,
                'INPUT': outputs['calculateG']['OUTPUT'],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
        outputs['calculateH'] = processing.run('native:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
        
        # calculateI: datetime (timestamp)
        if datatype == 'weather?':
            alg_params = {
                'FIELD_LENGTH': 20,
                'FIELD_NAME': 'datetime',
                'FIELD_PRECISION': 0,
                'FIELD_TYPE': 1,
                'FORMULA': dt,
                'INPUT': outputs['calculateH']['OUTPUT'],
                'OUTPUT': parameters['WeatherResult']
            }
        else:
            alg_params = {
                'FIELD_LENGTH': 20,
                'FIELD_NAME': 'datetime',
                'FIELD_PRECISION': 0,
                'FIELD_TYPE': 1,
                'FORMULA': dt,
                'INPUT': outputs['calculateH']['OUTPUT'],
                'OUTPUT': parameters['WeatherResult']
            }
        outputs['calculateI'] = processing.run('native:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
        results['WeatherResult'] = outputs['calculateI']['OUTPUT']
        
        return results

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'OpenWeather Current Data (SinglePoints)'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return ''
    def icon(self):
        cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]
        icon = QIcon(os.path.join(os.path.join(cmd_folder, 'weather.png')))
        return icon
        
    def tr(self, string):
        return QCoreApplication.translate('Processing', string)
        
    def shortHelpString(self):
        help_text = """               
        This algorithm tool will download two types of data from OpenWeather (https://openweathermap.org)
        (1) Weather Data (windspeed, winddirection,temperature, humidity, pressure, etc...)
        (2) Air Pollution Data (CO, NO, NO2, O3, SO2, PM2.5, PM10, NH3, etc...)
        
        **Output File Format: point with attribute infromation
        **Free Register at openweathermap.org and get the Free API Key
        As of Feb 2022, API key is required for all data. 
        
        
        Developed by: Htet Arkar Soe
        Date: 2022-02-23
        email: htetarkar.env.2016@gmail.com 

        """
        return self.tr(help_text)
    def createInstance(self):
        return OpenWeatherAlgorithm()
