# -*- coding: utf-8 -*-

"""
/***************************************************************************
 OpenWeather
                                 A QGIS plugin
 Downloading Weather Data From OpenWeather API
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-02-17
        copyright            : (C) 2022 by Htet Arkar Soe
        email                : htetarkar.env.2016@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Htet Arkar Soe'
__date__ = '2022-02-17'
__copyright__ = '(C) 2022 by Htet Arkar Soe'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import requests
import datetime
import time
import json
import csv
import os
import processing
import inspect
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFileDestination,
                       QgsProcessingMultiStepFeedback,
                       QgsProcessingParameterPoint,
                       QgsProcessingParameterString,
                       QgsCoordinateReferenceSystem,
                       QgsExpression,
                       QgsExpressionContext,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterEnum,
                       QgsProcessingParameterDateTime,
                       QgsSettings)

#from .functions import wind_deg, wind_speed

class HistOpenWeatherAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """
        my_settings = QgsSettings()
        my_api_key = my_settings.value("openWeather_api", "")
        if my_api_key=="":
            api_key_text = 'Enter your API key '
        else:
            api_key_text = 'Enter your API key or use existing one below'
        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(QgsProcessingParameterEnum('StartYear', 'From Year (available from November 27th, 2020)', 
                            options=['2020','2021','2022','2023'], 
                            allowMultiple=False, defaultValue=None
                            ))
        self.addParameter(QgsProcessingParameterEnum('StartMonth', 'From Month (available from November 27th, 2020)', 
                            options=['1','2','3','4','5','6','7','8','9','10','11','12'], 
                            allowMultiple=False, defaultValue=None
                            ))
        self.addParameter(QgsProcessingParameterEnum('StartDay', 'From Day (available from November 27th, 2020)', 
                            options=['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31'], 
                            allowMultiple=False, defaultValue=None
                            ))
        self.addParameter(QgsProcessingParameterEnum('EndYear', 'To Year (Any date starting from November 27th, 2020)', 
                            options=['2020','2021','2022','2023'], 
                            allowMultiple=False, defaultValue=None
                            ))
        self.addParameter(QgsProcessingParameterEnum('EndMonth', 'To Month (Any date starting from November 27th, 2020)', 
                            options=['1','2','3','4','5','6','7','8','9','10','11','12'], 
                            allowMultiple=False, defaultValue=None
                            ))
        self.addParameter(QgsProcessingParameterEnum('EndDay', 'To Day (Any date starting from November 27th, 2020)', 
                            options=['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31'], 
                            allowMultiple=False, defaultValue=None
                            ))
        self.addParameter(QgsProcessingParameterPoint('ChooseLocationOnMap', 'Choose Location On Map', defaultValue=''))
        self.addParameter(QgsProcessingParameterString('API_key', api_key_text, multiLine=False, defaultValue=my_api_key))
        self.addParameter(QgsProcessingParameterFileDestination(self.OUTPUT,self.tr('Output File'),'CSV files (*.csv)'))
        
    def processAlgorithm(self, parameters, context, model_feedback):
        """
        Here is where the processing itself takes place.
        """
        my_settings = QgsSettings()
        #feedback = QgsProcessingMultiStepFeedback(3, model_feedback)
        results = {}
        outputs = {}
        
        source = parameters['ChooseLocationOnMap']
        csvOutput = self.parameterAsFileOutput(parameters, self.OUTPUT, context)
        
        ## DownloadJSON
        epsg = source.split(' ')[1]
        epsg = epsg[1:-1] # strip off [ ]
        points = source.split(' ')[0].split(',')
        lat = points[1]
        lon = points[0]
        if not(epsg=='EPSG:4326'):
            lat_exp =  f'y(transform(make_point({lat},{lon}),\'{epsg}\',\'EPSG:4326\'))'
            lon_exp =  f'x(transform(make_point({lat},{lon}),\'{epsg}\',\'EPSG:4326\'))'
            context_exp = QgsExpressionContext()
            
            lat = QgsExpression(lat_exp).evaluate(context_exp)
            lon = QgsExpression(lon_exp).evaluate(context_exp)
        
        Start_YearIndex = ['2020','2021','2022','2023']
        Start_Year = Start_YearIndex[parameters['StartYear']]
        Start_MonthIndex = ['01','02','03','04','05','06','07','08','09','10','11','12']
        Start_Month =Start_MonthIndex[parameters['StartMonth']]
        Start_DayIndex = ['01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
        Start_Day =Start_DayIndex[parameters['StartDay']]
        
        End_YearIndex = ['2020','2021','2022','2023']
        End_Year = End_YearIndex[parameters['EndYear']]
        End_MonthIndex = ['01','02','03','04','05','06','07','08','09','10','11','12']
        End_Month =End_MonthIndex[parameters['EndMonth']]
        End_DayIndex = ['01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
        End_Day =End_DayIndex[parameters['EndDay']]
        
        start =time.mktime(datetime.datetime.strptime(f'{Start_Day}/{Start_Month}/{Start_Year}', "%d/%m/%Y").timetuple())
        end = time.mktime(datetime.datetime.strptime(f'{End_Day}/{End_Month}/{End_Year}', "%d/%m/%Y").timetuple())
        #2020-11-25 07:30:00
        
        #start = 1606223802 # starting date of data access by OpenWeather API
        #end = 1614025331 # today date
        #start = datetime.datetime.timestamp(Start_Date)
        #end = datetime.datetime.timestamp(End_Date)
        my_settings.setValue("openWeather_api", parameters['API_key'])
        apikey = parameters['API_key']
        params = {'lat':lat, 'lon':lon,'start':round(start),'end':round(end), 'appid':apikey}
        r = requests.get(f'https://api.openweathermap.org/data/2.5/air_pollution/history?',params=params)
        data = r.json()

        ## Create Variables for weather data
        #start_date = datetime.datetime.fromtimestamp(start)
        #end_date = datetime.datetime.fromtimestamp(end)
        #elasped = end_date-start_date
        num_days = len(data['list'])
        #print(num_days)
        count = 0
        header_added = False
        fields = ['co_μg/m3','no_μg/m3','no2_μg/m3','o3_μg/m3','so2_μg/m3','pm25_μg/m3','pm10_μg/m3','nh3_μg/m3','dt','lon','lat']
        while count < num_days:
            dt1 = data['list'][count]['dt']
            dt = datetime.datetime.fromtimestamp(dt1).strftime("%c")
            air =list(data['list'][count]['components'].values())
            air.append(dt)
            air.append(lon)
            air.append(lat)
            count += 1
            with open(csvOutput,'a') as f:
                if not header_added:
                    file = csv.writer(f)
                    file.writerow(fields)
                    header_added=True
                file = csv.writer(f)
                file.writerow(air)

        ## Load CSV into Project
        file_name = os.path.basename(csvOutput)
        alg_params = {           
            'INPUT': csvOutput,
            'NAME': file_name
        }
        outputs['LoadLayerIntoProject'] = processing.run('native:loadlayer', alg_params, context=context, feedback=model_feedback, is_child_algorithm=True)
      
        return results

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'OpenWeather AirPollution Data (Historical)'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return ''
        
    def icon(self):
        cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]
        icon = QIcon(os.path.join(os.path.join(cmd_folder, 'air.png')))
        return icon
        
    def tr(self, string):
        return QCoreApplication.translate('Processing', string)
    def shortHelpString(self):
        help_text = """               
        This algorithm tool will download historical air pollution data from OpenWeather (https://openweathermap.org). Historical data is accessible from 27th November 2020.
        
        
        **Air Pollution Data (CO, NO, NO2, O3, SO2, PM2.5, PM10, NH3, etc...)
        **Output File Format: csv, point
        **Free Register at openweathermap.org and get the Free API Key
        
        As of Feb 2022, API key is required for all data. 
        
        
        Developed by: Htet Arkar Soe
        Date: 2022-02-23
        email: htetarkar.env.2016@gmail.com 
        """
        return self.tr(help_text)
        
    def createInstance(self):
        return HistOpenWeatherAlgorithm()
